title:                            "OUDS Web Orange Business Tools"
baseURL:                          "https://web.unified-design-system.orange.com"
brand:                            "orange-business-tools"
display_brand:                    "Orange Business Tools"

docsDir:                          "site"

subtitle:                         "OUDS Web Orange Business Tools is a Bootstrap based, Orange Business Tools branded accessible and ergonomic components libraryâ€¦"
description:                      "Powerful, extensible, and feature-packed frontend toolkit. Build and customize with Sass, utilize prebuilt grid system and components, and bring projects to life with powerful JavaScript plugins."
authors:                          "Orange and OUDS Web Orange Business Tools contributors"

current_version:                  "1.0.0"
current_ruby_version:             "1.0.0"
docs_version:                     "1.0"
rfs_version:                      "v10.0.0"
bootstrap_current_version:        "5.3.6"
bootstrap_docs_version:           "5.3"
bootstrap_github_org:             "https://github.com/twbs"
repo:                             "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap"
x:                                "getbootstrap"
blog:                             "https://blog.getbootstrap.com/"
icons:                            "https://oran.ge/icons"
icons_develop:                    "https://design.orange.com/0c1af118d/p/12bc75-develop"
icons_license:                    "https://design.orange.com/0c1af118d/p/92bb17-usage/t/63532c"
icons_usage:                      "https://design.orange.com/0c1af118d/p/92bb17-usage"
bootstrap:                        "https://getbootstrap.com"
ouds:
  web:                            "https://unified-design-system.orange.com/"
debug_template:                   "https://codepen.io/louismaximepiton/pen/XJKpRqd"

algolia:
  app_id:                         "F4PKENW3TB"
  api_key:                        "d04e794979727856a09d53f12ead9069"
  index_name:                     "boosted-orange"

download:
  source:                         "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/archive/v1.0.0-ouds-web.zip"
  dist:                           "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v1.0.0-ouds-web/ouds-web-orange-business-tools-1.0.0-dist.zip"
  dist_examples:                  "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v1.0.0-ouds-web/ouds-web-orange-business-tools-1.0.0-examples.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:                            "https://cdn.jsdelivr.net/npm/@ouds/web-orange-business-tools@1.0.0/dist/css/ouds-web.min.css"
  css_hash:                       "sha384-jrGXgF9kcaOZ6+eUwML5UNeAysx377YxHY+EWnObISXQ1dmdXrK1iRRH36Oiq6bp"
  css_bootstrap:                  "https://cdn.jsdelivr.net/npm/@ouds/web-orange-business-tools@1.0.0/dist/css/ouds-web-bootstrap.min.css"
  css_bootstrap_hash:             "sha384-/sP1huIAS3Kd8ccu+f2AmgKA5CCR3Q81E3qnK9fq8uqUh44+lFrn3g4F9FXP+Sz3"
  css_bootstrap_rtl:              "https://cdn.jsdelivr.net/npm/@ouds/web-orange-business-tools@1.0.0/dist/css/ouds-web-bootstrap.rtl.min.css"
  css_bootstrap_rtl_hash:         "sha384-eJiwpXMxz084Toc0m+3gpyK0A5y7XfnlNMyrJGkKC2F4bVZHEhNTFpLH0/1Dr+wB"
  css_rtl:                        "https://cdn.jsdelivr.net/npm/@ouds/web-orange-business-tools@1.0.0/dist/css/ouds-web.rtl.min.css"
  css_rtl_hash:                   "sha384-QcwhfDgx6Y1S6SfOIiHoD6GdEoXWart1D8SVBm0+Z2Xv1WMMa0FH/14109lgoR7h"
  js:                             "https://cdn.jsdelivr.net/npm/@ouds/web-common@1.0.0/dist/js/ouds-web.min.js"
  js_hash:                        "sha384-Rs27admHe0B2LarwzYXf1BJdqD7OSswGJNpbxki7UZe7cnuctxZIcQRfMfhkr6fJ"
  js_bundle:                      "https://cdn.jsdelivr.net/npm/@ouds/web-common@1.0.0/dist/js/ouds-web.bundle.min.js"
  js_bundle_hash:                 "sha384-iouvBfNay/m9DC56jTa2kUblzVFnppFZ+nNu4BK8Txg/YNGcMZUVQfdy6FUwvNDj"
  popper:                         "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
  popper_hash:                    "sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
  popper_esm:                     "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js"

anchors:
  min:                  2
  max:                  5

toc:
  min:                  2
  max:                  6
