# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "site"
destination:    ./_gh_pages
host:           "localhost"
port:           9001
baseurl:        ""
# boosted mod
url:            "https://boosted.orange.com"
# end boosted mod
encoding:       UTF-8
exclude:
  - docs/4.4/assets/scss/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# boosted mod
grid:
  xs:
    breakpoint: 0
    width: 302
    gutter: 10
    desc: Extra small devices
    subdesc: Portrait phone (&lt;480px) (target 320 screen resolutions)
  sm:
    breakpoint: 480
    width: 458
    gutter: 10
    desc: Small devices
    subdesc: Landscape phones (&ge;480px - &lt;768px) (target 480 screen resolutions)
  md:
    breakpoint: 768
    width: 724
    gutter: 20
    desc: Medium devices
    subdesc: Tablet (&ge;768px - &lt;960px) (target 768 screen resolutions)
  lg:
    breakpoint: 980
    width: 960
    gutter: 20
    desc: Large devices
    subdesc: Desktop (&ge;960px - &lt;1120px) (target 1024 screen resolutions)
  xl:
    breakpoint: 1220
    width: 1180
    gutter: 20
    desc: Extra large devices
    subdesc: Desktop (&ge;1220px - &lt;1380px) (target 1280 screen resolutions)
  xxl:
    breakpoint: 1380
    width: 1300
    gutter: 20
    desc: Extra extra large devices
    subdesc: Desktop (&ge;1380px) (target 1440 screen resolutions)
# end boosted mod

# Social
title:              Boosted
description:        "Based on Bootstrap the most popular library."
twitter:            getbootstrap
authors:            "Mark Otto, Jacob Thornton, Bootstrap and Boosted contributors"
social_image_path:  /docs/4.4/assets/brand/orange_logo.jpg
social_logo_path:   /docs/4.4/assets/brand/orange_logo_social.jpg

# Custom variables
current_version:      4.4.0
current_ruby_version: 4.4.0
docs_version:         4.4
repo:                 "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap"
slack:                "https://bootstrap-slack.herokuapp.com"
opencollective:       "https://opencollective.com/bootstrap"
blog:                 "https://blog.getbootstrap.com"
expo:                 "https://expo.getbootstrap.com"
themes:               "https://themes.getbootstrap.com"
icons:                "https://icons.getbootstrap.com"

download:
  source:           "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/archive/v4.4.0.zip"
  dist:             "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v4.4.0/boosted-4.4.0-dist.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:               "https://cdn.jsdelivr.net/npm/boosted/dist/css/boosted.min.css"
  css_hash:          "sha384-VAtU9ZRKJTcfM4JHsCzDTZRZgdscAwNLn77yWBpR3BvCH4o2eCxVVp0i8EhkiBrC"
  iconcss:           "https://cdn.jsdelivr.net/npm/boosted/dist/css/orangeIcons.min.css"
  iconcss_hash:      "sha384-6aQI+svLMihLTITqNkBsRkem4Vy8KL1nnR9fa/CWOEeJzLY7U1JbnC3aX5u0hE97"
  helveticacss:      "https://cdn.jsdelivr.net/npm/boosted/dist/css/orangeHelvetica.min.css"
  helveticacss_hash: "sha384-e8MwV9etVvzgFAywWdlyEtXAdRYElY+BlimyrAcXkDiyJXy4oIZZqrV/ST605uwF"
  js:                "https://cdn.jsdelivr.net/npm/boosted/dist/js/boosted.min.js"
  js_hash:           "sha384-mtmGDb9qalJeocSwW+VFsFUaXKMIItvPRHgGn87RVnoYZz/8D42oMV65Qse6yJt5"
  js_bundle:         "https://cdn.jsdelivr.net/npm/boosted@4.4.0/dist/js/boosted.bundle.min.js"
  js_bundle_hash:    "sha384-xbvihzha8ShwGdBgk4dOni196Hl/AYymEmzTM9YYAvfcy/buOrVsVi9OPeIMcbyO"
  jquery:            "https://code.jquery.com/jquery-3.4.1.slim.min.js"
  jquery_hash:       "sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
  jquery_full:       "https://code.jquery.com/jquery-3.4.1.min.js"
  jquery_full_hash:  "sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  css_swiper:        "https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/css/swiper.min.css"
  css_swiper_hash:   "sha384-K6LrEaceM4QP87RzJ7R4CDXcFN4cFW/A5Q7/fEp/92c2WV+woVw9S9zKDO23sNS+"
  js_swiper:         "https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/js/swiper.min.js"
  js_swiper_hash:    "sha384-fOtis9P3S4B2asdoye1/YBpXMaRmuXu925gZhfQA/gnU3dLnftD8zvpk/lhP0YSG"
  popper:            "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js"
  popper_hash:       "sha384-L2pyEeut/H3mtgCBaUNw7KWzp5n9+4pDQiExs933/5QfaTh8YStYFFkOzSoXjlTb"
  tablesorter:       "https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.31.1/js/jquery.tablesorter.min.js"
  tablesorter_hash:  "sha384-QnFIXbEfAgO7z63b/aNzTSdSNLoNiNX/mk/Ok+NpUNMnvriWLo5cOtB0OUCAdKNu"
  focusvisible:      "https://cdn.jsdelivr.net/npm/focus-visible@5.0.2/dist/focus-visible.min.js"
  focusvisible_hash: "sha256-sz9/xSAM6mrw3l6hJWDgc7nEbzUeO5e8CXwYoECOEKI="

toc:
  min_level:        2
  max_level:        4
  no_toc_section_class:
    - "bd-callout"
    - "bd-example"
