title:                            "OUDS Web"
baseURL:                          "https://web.unified-design-system.orange.com"
brand:                            "orange"
display_brand:                    "Orange"

docsDir:                          "site"

subtitle:                         "OUDS Web is a Bootstrap based, Orange branded accessible and ergonomic components libraryâ€¦"
description:                      "Powerful, extensible, and feature-packed frontend toolkit. Build and customize with Sass, utilize prebuilt grid system and components, and bring projects to life with powerful JavaScript plugins."
authors:                          "Orange and OUDS Web contributors"

current_version:                  "1.0.0"
current_ruby_version:             "1.0.0"
docs_version:                     "1.0"
rfs_version:                      "v10.0.0"
bootstrap_current_version:        "5.3.6"
bootstrap_docs_version:           "5.3"
bootstrap_github_org:             "https://github.com/twbs"
repo:                             "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap"
x:                                "getbootstrap"
blog:                             "https://blog.getbootstrap.com/"
icons:                            "https://oran.ge/icons"
icons_develop:                    "https://design.orange.com/0c1af118d/p/12bc75-develop"
icons_license:                    "https://design.orange.com/0c1af118d/p/92bb17-usage/t/63532c"
icons_usage:                      "https://design.orange.com/0c1af118d/p/92bb17-usage"
bootstrap:                        "https://getbootstrap.com"
ouds:
  web:                            "https://unified-design-system.orange.com/"
debug_template:                   "https://codepen.io/louismaximepiton/pen/WbreEwY"

algolia:
  app_id:                         "AKIHKMSEKB"
  api_key:                        "8863f72a6120798814c9bd8353ba50f5"
  index_name:                     "Orange crawler"

download:
  source:                         "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/archive/v1.0.0-ouds-web.zip"
  dist:                           "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v1.0.0-ouds-web/ouds-web-orange-1.0.0-dist.zip"
  dist_examples:                  "https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/releases/download/v1.0.0-ouds-web/ouds-web-orange-1.0.0-examples.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:                            "https://cdn.jsdelivr.net/npm/@ouds/web-orange@1.0.0/dist/css/ouds-web.min.css"
  css_hash:                       "sha384-VDd+lWwqszAtzv4tEgXNTBJ9s5m0usxIf4sSGCxCp7fjxbeNfR4Z7yQhQoNucdJG"
  css_bootstrap:                  "https://cdn.jsdelivr.net/npm/@ouds/web-orange@1.0.0/dist/css/ouds-web-bootstrap.min.css"
  css_bootstrap_hash:             "sha384-+9gPjZSojYMiLC0SIkBIPDYzzoi7wY/TWmsFrmt16Un8nRG/icS5/vp456OmGsel"
  css_bootstrap_rtl:              "https://cdn.jsdelivr.net/npm/@ouds/web-orange@1.0.0/dist/css/ouds-web-bootstrap.rtl.min.css"
  css_bootstrap_rtl_hash:         "sha384-mo4HnQVqW58BqLxS1taJV3xYEUOpyUK6PmXJs+OSntGFv3FXtxb57x3Who/Fdipa"
  css_rtl:                        "https://cdn.jsdelivr.net/npm/@ouds/web-orange@1.0.0/dist/css/ouds-web.rtl.min.css"
  css_rtl_hash:                   "sha384-4XMLV+aVpisWipvXsM7wz3znawPdRaQgL4kRbv2n5RN2/Vfck59uiLFH6Ju1rj1d"
  js:                             "https://cdn.jsdelivr.net/npm/@ouds/web-common@1.0.0/dist/js/ouds-web.min.js"
  js_hash:                        "sha384-Rs27admHe0B2LarwzYXf1BJdqD7OSswGJNpbxki7UZe7cnuctxZIcQRfMfhkr6fJ"
  js_bundle:                      "https://cdn.jsdelivr.net/npm/@ouds/web-common@1.0.0/dist/js/ouds-web.bundle.min.js"
  js_bundle_hash:                 "sha384-iouvBfNay/m9DC56jTa2kUblzVFnppFZ+nNu4BK8Txg/YNGcMZUVQfdy6FUwvNDj"
  popper:                         "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
  popper_hash:                    "sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
  popper_esm:                     "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js"

anchors:
  min:                  2
  max:                  5

toc:
  min:                  2
  max:                  6
