name: Publish NuGet Packages

on:
  release:
    types: [published]

jobs:
  package-nuget:
    runs-on: windows-latest
    if: ${{ github.repository == 'Orange-OpenSource/Orange-Boosted-Bootstrap' && startsWith(github.event.release.tag_name, 'v') }}
    env:
      GITHUB_REF_NAME: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up NuGet
        uses: nuget/setup-nuget@323ab0502cd38fdc493335025a96c8fdb0edc71f # v2.0.1
        with:
          nuget-api-key: ${{ secrets.NUGET_TOKEN }}
          nuget-version: '5.x'

      - name: Pack NuGet packages
        shell: pwsh
        run: |
          $bsversion = $env:GITHUB_REF_NAME.Substring(1)
          nuget pack "nuget\ouds-web-common.nuspec" -Verbosity detailed -NonInteractive -BasePath . -Version $bsversion
          nuget pack "nuget\ouds-web-common.sass.nuspec" -Verbosity detailed -NonInteractive -BasePath . -Version $bsversion
          nuget pack "packages\orange\nuget\ouds-web-orange.nuspec" -Verbosity detailed -NonInteractive -BasePath . -Version $bsversion
          nuget pack "packages\orange\nuget\ouds-web-orange.sass.nuspec" -Verbosity detailed -NonInteractive -BasePath . -Version $bsversion
          nuget pack "packages\orange-compact\nuget\ouds-web-orange-compact.nuspec" -Verbosity detailed -NonInteractive -BasePath . -Version $bsversion
          nuget pack "packages\orange-compact\nuget\ouds-web-orange-compact.sass.nuspec" -Verbosity detailed -NonInteractive -BasePath . -Version $bsversion
          nuget pack "packages\sosh\nuget\ouds-web-sosh.nuspec" -Verbosity detailed -NonInteractive -BasePath . -Version $bsversion
          nuget pack "packages\sosh\nuget\ouds-web-sosh.sass.nuspec" -Verbosity detailed -NonInteractive -BasePath . -Version $bsversion
          nuget push "ouds-web-common.$bsversion.nupkg" -Verbosity detailed -NonInteractive -Source "https://api.nuget.org/v3/index.json"
          nuget push "ouds-web-common.sass.$bsversion.nupkg" -Verbosity detailed -NonInteractive -Source "https://api.nuget.org/v3/index.json"
          nuget push "ouds-web-orange.$bsversion.nupkg" -Verbosity detailed -NonInteractive -Source "https://api.nuget.org/v3/index.json"
          nuget push "ouds-web-orange.sass.$bsversion.nupkg" -Verbosity detailed -NonInteractive -Source "https://api.nuget.org/v3/index.json"
          nuget push "ouds-web-orange-compact.$bsversion.nupkg" -Verbosity detailed -NonInteractive -Source "https://api.nuget.org/v3/index.json"
          nuget push "ouds-web-orange-compact.sass.$bsversion.nupkg" -Verbosity detailed -NonInteractive -Source "https://api.nuget.org/v3/index.json"
          nuget push "ouds-web-sosh.$bsversion.nupkg" -Verbosity detailed -NonInteractive -Source "https://api.nuget.org/v3/index.json"
          nuget push "ouds-web-sosh.sass.$bsversion.nupkg" -Verbosity detailed -NonInteractive -Source "https://api.nuget.org/v3/index.json"
